### ISSUE TITLE
Add proxy address or key, README.md supplement instructions.

### ISSUE THREAD

**Issue by Jialin0502** [hkurma/openai-playground-plus#2]
Hello developer 🥰 , this is some suggestions, please check ~ (Translate by Google)

1. API address can be customized, thus  can don’t need to fill in the api key or use it in inaccessible areas.
For example, in the [next chat](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/blob/main/README.md) project, it can directly use vercel to forward, use Environmane Variables, and add password protection to prevent abuse.

2. add more detailed README:

#### Build

This project uses Vercel's [next.js](https://nextjs.org/docs/getting-started/installation) to deploy the hosting with Vercel.

The default construction will not be exported static

```bash
npm run build
```

Next.js can be started as a static site or single -page application (SPA), so it can deploy and host on a web server that supports HTML/CSS/JS static assets.
To enable static export, change the next.config.js file.

```js
/**
  * @Type {Import ('Next'). NextConfig}
  */
const nextconfig = {
   output: 'Export',
}
 
module.exports = nextconfig
```

Construction again will generate the /out folder, which contains resources such as HTML/CSS/JS of the program.

### Tip: Translate by Google, may be wrong, hope you understand.

**Comment by harishkurma-se** [comment]
@Jialin0502 - Please feel free to make changes and create a PR.
